spring:
  application:
    name: ultra-coin
  datasource :
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: adm240
    url: jdbc:mysql://localhost/ultra_coin?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: ultra_coin_topic

  server:
    port: 8081


