spring:
  application:
    name: ultra-coin
  datasource :
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: adm240
    url: jdbc:mysql://localhost/ultra_coin?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  server:
    port: 8080


